In [1]:
#importing libararies 
import pandas as pd
import numpy as np 

In [2]:
# read the data into dataframe
data=pd.read_excel('data.xlsx')

In [3]:
# get the first 5 rows
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   
4    -122.25     37.85                  52         1627           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0         322         126         8.3252              452600        NEAR BAY  
1        2401        1138         8.3014              358500        NEAR BAY  
2         496         177         7.2574              352100        NEAR BAY  
3         558         219         5.6431              341300        NEAR BAY  
4         565         259         3.8462              342200        NEAR BAY

#### What's the version of Pandas that you installed?

In [4]:
print('pandas version :',pd.__version__)

pandas version : 1.5.3


#### How many columns are in the dataset?

In [5]:
print ('the number of columns is :', data.shape[1])

the number of columns is : 10


#### Which columns in the dataset have missing values?

In [6]:
data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

#### How many unique values does the ocean_proximity column have?

In [7]:
data.ocean_proximity.value_counts()         

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

#### What's the average value of the median_house_value for the house located near the bay?

In [8]:
round(data['median_house_value'].groupby(data.ocean_proximity).mean(),2)

ocean_proximity
<1H OCEAN     240084.29
INLAND        124805.39
ISLAND        380440.00
NEAR BAY      259212.31
NEAR OCEAN    249433.98
Name: median_house_value, dtype: float64

#### Calculate the average of total_bedrooms column in the dataset.

In [9]:
round(data.total_bedrooms.mean(),3)

537.871

In [10]:
data.total_bedrooms=data.total_bedrooms.fillna(data.total_bedrooms.mean() )

In [11]:
data.total_bedrooms.isnull().sum()

0

In [12]:
round(data.total_bedrooms.mean(),3)

537.871

#### Select all the options located on islands.

In [13]:
data[data['ocean_proximity']=='ISLAND']

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                  27         1675           521.0   
8315    -118.33     33.34                  52         2359           591.0   
8316    -118.32     33.33                  52         2127           512.0   
8317    -118.32     33.34                  52          996           264.0   
8318    -118.48     33.43                  29          716           214.0   

      population  households  median_income  median_house_value  \
8314         744         331         2.1579              450000   
8315        1100         431         2.8333              414700   
8316         733         288         3.3906              300000   
8317         341         160         2.7361              450000   
8318         422         173         2.6042              287500   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [14]:
####Select only columns housing_median_age, total_rooms, total_bedrooms.

In [17]:
data=data[['housing_median_age','total_rooms','total_bedrooms']].head()
data

housing_median_age  total_rooms  total_bedrooms
0                  41          880           129.0
1                  21         7099          1106.0
2                  52         1467           190.0
3                  52         1274           235.0
4                  52         1627           280.0

#### Get the underlying NumPy array. Let's call it X.

In [43]:
x=np.array(data)
x

array([[  41.,  880.,  129.],
       [  21., 7099., 1106.],
       [  52., 1467.,  190.],
       [  52., 1274.,  235.],
       [  52., 1627.,  280.]])

In [44]:
xt=np.matrix.transpose(x)

In [45]:
xt

array([[  41.,   21.,   52.,   52.,   52.],
       [ 880., 7099., 1467., 1274., 1627.],
       [ 129., 1106.,  190.,  235.,  280.]])

In [47]:
xtx = np.dot(xt, x)
xtx_inverse = np.linalg.inv(xtx)

In [48]:
y=np.array([950, 1300, 800, 1000, 1300])

In [49]:
y

array([ 950, 1300,  800, 1000, 1300])

In [ ]:
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [53]:
w = np.dot(np.dot(np.linalg.inv(xtx), xt), y)
w

array([16.46449939, -0.4502882 ,  3.75303243])